### ISSUE TITLE
Making sure the template has been successfuly added before close the modal

### ISSUE THREAD

**Issue by stidiovip** [voyages-sncf-technologies/hesperides-gui#76] opened 2017-01-25 11:12 UTC
In hesperides, the modal for adding template is closed whether the template is added or not. 
It will be very useful to not close the modal when the template adding has failed. So the user do not loose his data.

**Comment by stidiovip** [comment] 2017-01-25 12:55
Juste remove "SAVE AND CLOSE" button ?

**Comment by JordanKergoat** [comment] 2017-02-03 16:13
I would rather keep this button, but make sure the template has been successfully updated/created before closing the modal.

Doing it that way, the user will be able to see the error notification, and apply the right fix before saving again. 

If the issue is about non synchronized view against the remote version, actually we don't have any choice but refresh the page to get up to date information (but the user will loose his modifications). Possible fix, try to create a version of the local change in application on this section too.

**Closed** 2017-04-03 13:20 UTC
Labels: enhancement
