### ISSUE TITLE
Can error properties without error

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides-gui#110] opened 2017-05-17 12:43 UTC
For example, if I display global properties but, my web brower can't get properties (this call never response http://localhost:8080/rest/applications/KTN/platforms/USN1/properties?path=%23 because Hesperides is down or network cut).

I can add a properties and send it.

When we push data, we set platform_id, but platform_id is get before get data.

That mean is work and errase data.

**Comment by Lucas-C** [comment] 2018-10-30 13:21
Cannot reproduce, closing

**Closed by Lucas-C** 2018-10-30 13:21 UTC
Labels: bug
